### ISSUE TITLE
Build creating container image fails with version 5.19.0

### ISSUE THREAD

**Issue by pppoudel** [paketo-buildpacks/azure-application-insights#330]
We are using paketo buildpacks to create our container image for Java Springboot application. paketo-buildpacks/azure-application-insights is one of the buildpacks included to create our container image. Our Azue DevOps pipeline create container image using spring boot command “mvn spring-boot:build-image”.

Here is our “spring-boot-maven-plugin” config:

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <buildpacks>
                            <buildpack>paketo-buildpacks/ca-certificates</buildpack>
                            <buildpack>gcr.io/paketo-buildpacks/microsoft-openjdk</buildpack> 
                            <buildpack>paketo-buildpacks/syft</buildpack>
                            <buildpack>paketo-buildpacks/executable-jar</buildpack>
                            <buildpack>paketo-buildpacks/dist-zip</buildpack>
                            <buildpack>paketo-buildpacks/spring-boot</buildpack>
                            <buildpack>gcr.io/paketo-buildpacks/azure-application-insights</buildpack>
                        </buildpacks>
                        <createdDate>now</createdDate>
                        <bindings>${project.basedir}/appinsights:/platform/bindings/application-insights</bindings>
                    </image>
                </configuration>
            </plugin>
Creating container image was working fine until few days ago. But suddenly it started failing. When we looked, we found the difference between the last successful build and the failed one is the Azure App Insight buildpack version. The build was successful with version 5.18.3 but failing with version “5.19.0”.  See failure message below;

## Expected Behavior
Successfully create container image and include Azure App Insight Jar in the image.

## Possible Solution
Image creation fails with "open /cnb/buildpacks/paketo-buildpacks_azure-application-insights/5.19.0/resources/AI-Agent.xml: no such file or directory". See the error details:

[INFO] [creator] 
[INFO] [creator] Paketo Buildpack for Azure Application Insights 5.19.0 
[INFO] [creator] https://github.com/paketo-buildpacks/azure-application-insights 
[INFO] [creator] Azure Application Insights Java Agent 3.5.1: Contributing to layer 
[INFO] [creator] Downloading from https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.5.1/applicationinsights-agent-3.5.1.jar 
[INFO] [creator] Verifying checksum 
[INFO] [creator] Copying to /layers/paketo-buildpacks_azure-application-insights/azure-application-insights-java 
[INFO] [creator] unable to invoke layer creator 
[INFO] [creator] unable to open /cnb/buildpacks/paketo-buildpacks_azure-application-insights/5.19.0/resources/AI-Agent.xml 
[INFO] [creator] open /cnb/buildpacks/paketo-buildpacks_azure-application-insights/5.19.0/resources/AI-Agent.xml: no such file or directory 
[INFO] [creator] ERROR: failed to build: exit status 1 

## Steps to Reproduce
Our build process runs with Java 17, Spring boot 3.2 on Ubuntu Linux and we use “mvn spring-boot:build-image” command to create the image. See above the definition of 'spring-boot-maven-plugin'

Also, wondering is there a way to define the specific version of azure-application-insights build pack in spring-boot-maven-plugin in 'pom.xml?

**Comment by dmikusa** [comment]
Apologizes. We had an issue with changes in the last round of buildpacks, and are working on a fix.

In the meantime, you can rollback and use the previous version of the buildpack.

- https://github.com/paketo-buildpacks/azure-application-insights/releases/tag/v5.18.3

**Comment by anthonydahanne** [comment]
hello!
it was fixed in `5.19.1` or `latest` at the moment
Let us know if you find any other issues! thanks!
